### ISSUE TITLE
Filter_entity and DQL

### ISSUE THREAD

**Issue by Guilain** [lexik/LexikFormFilterBundle#137]
Hi,

I have a select I filled via ajax :
`->add('commune', 'filter_entity', [
    "class"       => "MainGeoBundle:Commune",
    "empty_value" => "Villes",
    "choices"     => []
])`

Form data are well sent :
`'annonces_terrainbundle_annonce_filter[commune]:12293'`

But the DQL isn't populated with this type, others works great.

**Comment by Rvanlaak** [comment]
You can use the `apply_filter` option if you don't want to add choices already.

**Comment by Guilain** [comment]
i don't see how ...

**Comment by cedric-g** [comment]
Hi, your problem is that when you submit your form the `commune` field don't have any choices so the submitted value is not binded and so no condition is added for this field (the `entity` type checks the submitted value is in the choices set).

This should help you : http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html#cookbook-form-events-submitted-data

**Comment by Guilain** [comment]
C'est bon ça fonctionne, j'avais effectivement oublié cette option... Merci pour ton aide :)
