### ISSUE TITLE
Symfony 3.1 compatibility

### ISSUE THREAD

**Issue by Timo-Linde** [lexik/LexikFormFilterBundle#227]
The choices_as_values option of the ChoiceType has been deprecated and will be removed in Symfony 4.0.

Used in:
Filter/Form/Type/TextFilterType.php:53
Filter/Form/Type/BooleanFilterType.php:47
Filter/Form/Type/NumberFilterType.php:55

https://github.com/symfony/symfony/blob/master/UPGRADE-3.1.md#form

**Comment by rvanlaak** [comment]
As long as the bundle still supports Symfony form `~2.8` this option should stay available. 

Only once that requirement is bumped to `~3.0` these three lines of code can be removed because they do not affect any of the form's behavior:

https://github.com/lexik/LexikFormFilterBundle/search?utf8=%E2%9C%93&q=choices_as_values
