### ISSUE TITLE
Mongo as separate packages?

### ISSUE THREAD

**Issue by snebes** [lexik/LexikFormFilterBundle#307]
I want to propose moving the Mongo functionality into a separate package.  This way, the user can choose which Mongo extension they are working with, as the current implementation isn't compatible with the newer `php-mongodb` extension.  These would be "add-on" packages using the adapter pattern.

This would simplify further development work on the main package, and open the possibility for even more adapters.

Thoughts?

**Comment by spike31** [comment]
@snebes I have revert your PR #308 , my bad..

Because you have add a requirement on doctrine odm bundle.

You cannot force someone to have the php mongodb extension  to use this bundle.
Did you understand the problem?

Maybe you need to re-open a PR from your old branch for fix the deps.

----------------
For your propose it's not a problem about php mongo-ext, because the only deps with that lib is doctrine odm bundle who have a requirement with doctrine odm. 

Lexik bundle just use doctrine odm bundle, it's just know about what to do with the bundle, not about how the bundle works in internal.

**Comment by snebes** [comment]
I understand - it would impose installing that when not in use.  I've added a new PR #311 where that is moved back into `require-dev`.

I would also recommend merging #304 as it is another Symfony deprecation.
