### ISSUE TITLE
Use Select2 on the select entity filters

### ISSUE THREAD

**Issue by rvanlaak** [lexik/LexikFormFilterBundle#64]
When the select fields contain many entities, it is difficult to find the right option. It would be great if optionally the select2 bundle can be implemented. This great jQuery selectbox replacement makes it possible to type in the select-box.

http://ivaynberg.github.io/select2/

I've already implemented it myself now, but via a workaround instead of directly into the filter bundle. It can be an parameter in the constructor of the filter field.

**Comment by webdevilopers** [comment]
It is often discussed wheter JS libraries should be included or bound to a bundle.
Looking at `SonataAdminBundle` `select2` has become default on Autocompleters - which is awesome!

If we consider adding `select2` we needed two features:
- auto generating the JS for the autocomplete
- calling a controller or event that creates json data for the requested filter e.g. `filter_entity`

Maybe this can be achieved by an additional bundle.

If we had this feature inside THIS bundle it would be a great package since it solves a lot of use cases, would save time writing the JS and improve performance for large `select` fitlers.

**Comment by Rvanlaak** [comment]
I'm still in favor of adding select2 to this bundle by default, given that `SonataAdmin` did also choose for it. But it should be configurable.

Otherwise :+1: for an additional bundle, which will be a `LexikFormFilterExtraBundle` right? It could be suggested by the composer.json of this bundle.

**Comment by webdevilopers** [comment]
Let's see what @cedric-g thinks. :+1:

**Comment by cedric-g** [comment]
I still have the same opinion, but if you really think it's a good thing to provide a select2 integration feel free to submit a PR :)
